Add support for collecting core info on Solaris
Change-Id: I8cc85f3877db9af4ed4d7f88413ba5ce7224d83d
Reviewed-on: http://review.couchbase.org/7122
Reviewed-by: Matt Ingenthron <matt@couchbase.com>
Tested-by: Trond Norbye <trond.norbye@gmail.com>

diff --git a/management/analyze_core b/management/analyze_core
--- a/management/analyze_core
+++ b/management/analyze_core
@@ -46,11 +46,6 @@ then
    usage
 fi
 
-if [ -z "${root}" ]
-then
-   root=`dirname "${corefile}"`
-fi
-
 if [ -z "${report}" ]
 then
    report=${corefile}.log
@@ -69,42 +64,12 @@ then
    exit 1
 fi
 
-ls "${root}" >/dev/null 2>&1
-if [ $? -ne 0 ]
+digest -l 2>&1 > /dev/null
+if [ $? -eq 0 ]
 then
-   echo "Couchbase root directory (${root}) doesn't exist"
-   exit 1
-fi
-
-cmdfile=/tmp/gdb-commands.$$
-cat > $cmdfile <<EOF
-info auxv
-EOF
-binary=`gdb --core "${corefile}" --batch -x $cmdfile | grep AT_EXECFN | cut -f2 -d\"`
-rm $cmdfile
-if [ "x${binary}" = "x" ]
-then
-   binary_name=`file ${corefile} | cut -f 2 -d \'`
-   binary=`(cd ${root} && find . -type f -name "${binary_name}" | head -n1)`
-   if [ "x${binary}" = "x" ]
-   then
-       echo "Failed to determine the binary name from the corefile"
-       exit 1
-   fi
-fi
-
-if [ `echo "${binary}" | cut -c1` = "/" ]
-then
-  executable="${binary}"
+   digest="digest -a md5"
 else
-  executable=`ls "${root}/${binary}" 2>/dev/null`
-fi
-
-if [ "x${executable}" = "x" ]
-then
-   echo "Failed to locate the binary for the corefile."
-   echo "Your tools might be broken. Consider sending core dump to support@couchbase.com."
-   exit 1
+   digest="md5sum"
 fi
 
 cat > ${report}  <<EOF
@@ -116,39 +81,128 @@ Please send the file to support@couchbase.com
 File information:
 EOF
 
-ls -l ${executable} ${corefile} >> ${report}
-md5sum ${executable} >> ${report}
-md5sum ${corefile} >> ${report}
-strings ${executable} | egrep '[0-9]+\.[0-9]+\.[0-9]+_[0-9]+_........' >> ${report}
+dump_file() {
+   ls -l $1 >> ${report}
+   ${digest} $1 >> ${report}
+   strings $1 | egrep '[0-9]+\.[0-9]+\.[0-9]+_[0-9]+_........' >> ${report}
+}
 
-cat >> ${report} <<EOF
+#######################################################################
+# Function to get information about the binaries by using gdb...
+#######################################################################
+analyze_gdb() {
+   if [ -z "${root}" ]
+   then
+      root=`dirname "${corefile}"`
+   fi
+
+   ls "${root}" >/dev/null 2>&1
+   if [ $? -ne 0 ]
+   then
+      echo "Couchbase root directory (${root}) doesn't exist"
+      exit 1
+   fi
+
+   cmdfile=/tmp/gdb-commands.$$
+   cat > $cmdfile <<EOF
+info auxv
+EOF
+   binary=`gdb --core "${corefile}" --batch -x $cmdfile | grep AT_EXECFN | cut -f2 -d\"`
+   rm $cmdfile
+   if [ "x${binary}" = "x" ]
+   then
+      binary_name=`file ${corefile} | cut -f 2 -d \'`
+      binary=`(cd ${root} && find . -type f -name "${binary_name}" | head -n1)`
+      if [ "x${binary}" = "x" ]
+      then
+         echo "Failed to determine the binary name from the corefile"
+         exit 1
+      fi
+   fi
+
+   if [ `echo "${binary}" | cut -c1` = "/" ]
+   then
+      executable="${binary}"
+   else
+      executable=`ls "${root}/${binary}" 2>/dev/null`
+   fi
+
+   if [ "x${executable}" = "x" ]
+   then
+      echo "Failed to locate the binary for the corefile."
+      echo "Your tools might be broken. Consider sending core dump to support@couchbase.com."
+      exit 1
+   fi
+
+   dump_file ${executable}
+   dump_file ${corefile}
+
+   cat >> ${report} <<EOF
 --------------------------------------------------------------------------------
 Core file callstacks:
 EOF
 
-cmdfile=/tmp/gdb-commands.$$
-cat > $cmdfile <<EOF
+   cmdfile=/tmp/gdb-commands.$$
+   cat > $cmdfile <<EOF
 thread apply all bt
 quit
 EOF
-gdb --command=$cmdfile ${executable} ${corefile} >> ${report} 2>&1
-rm $cmdfile
+   gdb --command=$cmdfile ${executable} ${corefile} >> ${report} 2>&1
+   rm $cmdfile
 
-cat >> ${report} <<EOF
+   cat >> ${report} <<EOF
 --------------------------------------------------------------------------------
 Module information:
 EOF
-mlines=`grep "^Loaded symbols for " ${report}`
-for module in $mlines
-do
-   if [ "$module" != "Loaded" -a "$module" != "symbols" -a "$module" != "for" ]
-   then
-      echo ${module}:
-      (cd "${root}" && ls -l ${module})
-      (cd "${root}" && strings ${module}) | egrep '[0-9]+\.[0-9]+\.[0-9]+_[0-9]+_........'
-      (cd "${root}" && md5sum ${module})
-   fi
-done >> ${report}
+   mlines=`grep "^Loaded symbols for " ${report}`
+   for module in $mlines
+   do
+      if [ "$module" != "Loaded" -a "$module" != "symbols" -a "$module" != "for" ]
+      then
+         echo ${module}:
+         (cd "${root}" && dump_file ${module})
+      fi
+   done >> ${report}
+}
+
+#######################################################################
+# Function to get information about the binaries used from a Solaris
+# system
+#######################################################################
+analyze_sunos() {
+executable=`pldd ${corefile} | head -1 | tr -d '[\t]' | cut -f 2 -d: | cut -f 1 -d \ `
+   dump_file ${executable}
+   dump_file ${corefile}
+   cat >> ${report} <<EOF
+--------------------------------------------------------------------------------
+Core file callstacks:
+EOF
+   pstack ${corefile} >> ${report} 2>&1
+   cat >> ${report} <<EOF
+--------------------------------------------------------------------------------
+Module information:
+EOF
+   mlines=`pldd ${corefile} | grep -v "^core "`
+   for module in $mlines
+   do
+      dump_file ${module}
+   done >> ${report}
+
+   cat >> ${report} <<EOF
+--------------------------------------------------------------------------------
+Potential memory leaks:
+EOF
+   echo ::findleaks -v -d | mdb ${corefile} >> ${report} 2>&1
+}
+
+case `uname -s` in
+  SunOS)
+    analyze_sunos
+    ;;
+  *)
+    analyze_gdb
+    ;;
+esac
 
 cat <<EOF
 
